---
baseurl: /product-design
name: Centro Prototypes
permalink: /:categories/:month-:day-:year/:title/
exclude:
- Gemfile
- Gemfile.lock
- product-design.esproj
- publish.sh
assets:
  compress:
    css: sass
    js: uglifier
  baseurl: /product-design/assets/
  cache_assets: true
  sources:
  - _assets/javascripts
  - _assets/javascripts/vendor
  - _assets/stylesheets
  - _assets/fonts
  - _assets/images
  - _assets/images/2013-07-12-messaging-redux
  - _assets/images/2013-07-16-auth-user-admin
  - _assets/images/2013-08-06-ad-server-management
  - _assets/images/2013-08-07-ad-server-mapping
  - _assets/images/2013-08-07-ad-server-api-settings
  - _assets/images/2013-08-13-date-picker-widget
  - _assets/images/2013-08-16-campaign-notes
  - _assets/images/2013-05-16-campaign-quick-search
  - _assets/images/2013-09-09-campaign-totals
  - _assets/images/2013-09-16-reminders
  - _assets/images/2013-09-19-basic-suite-nav
  - _assets/images/2013-09-25-low-fi-suite-vision
  - _assets/images/2013-09-30-low-fi-vision-revised
  - _assets/images/.2013-09-30-low-fi-vision-revised.swp
